# Generated by Django 3.0.2 on 2020-01-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MandarinWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplified', models.CharField(max_length=20)),
                ('traditional', models.CharField(max_length=20)),
                ('pronunciation', models.CharField(max_length=80)),
                ('definition', models.TextField()),
            ],
        ),
    ]
